export enum ParserEvent {
  NAME = "NAME",
  OPEN_BRACE = "OPEN_BRACE",
  CLOSED_BRACE = "CLOSED_BRACE",
  OPEN_PAREN = "OPEN_PAREN",
  CLOSED_PAREN = "CLOSED_PAREN",
  OPEN_ANGLE = "OPEN_ANGLE",
  CLOSED_ANGLE = "CLOSED_ANGLE",
  DASH = "DASH",
  EOF = "EOF",
  COLON = "COLON",
}
